Switch to circle ci 2

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,3 +1,20 @@
+install_composer: &install_composer
+    command: |
+        cd /tmp
+        EXPECTED_SIGNATURE=$(curl -q https://composer.github.io/installer.sig)
+        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+        ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
+        if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
+        then
+            >&2 echo 'ERROR: Invalid installer signature'
+            rm composer-setup.php
+            exit 1
+        fi
+        sudo php composer-setup.php --quiet --install-dir /usr/local/bin --filename composer
+        RESULT=$?
+        rm composer-setup.php
+        exit $RESULT
+
 version: 2
 jobs:
     build:
@@ -5,6 +22,8 @@ jobs:
         - image: circleci/php:5.6.30
       steps:
         - checkout
+        - run:
+            <<: *install_composer
         - run:
             name: Setup Sonar
             command: sh ./bin/deployment/setup_sonar.sh
